version: '3.8'
services:
  db:
    build: .
    container_name: test_animemovies
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: test-anime-movies
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3309:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
